### ISSUE TITLE
Convert mnc to nift for fmriprep

### ISSUE THREAD

**Issue by zhengchencai** [BIC-MNI/minc-toolkit-v2#141]
Hi there, 

I'd like to use fmriprep to preprocess fMRI data. However, they support BIDS which means I need to first convert my mnc MRI images to nii. So I installed a docker container of minctool (nistmni/minc-toolkit-min:1.9.16) and converted one T1 mnc file to nii, but the output image got rotated. From the output message, it seems a transformation was applied but I don't know why and how to avoid this. Could you please help? 

nistmni@f77d21428da6:/files_to_convert/ep0588_30_08_2007/anatomical$ mnc2nii sub01_anatomical.mnc sub02_anatomical.nii
found zspace at 0 0
found yspace at 1 1       
found xspace at 2 2     
0 2 0 1 100 1.250000  
1 1 1 1 256 1.250000   
2 0 2 1 256 1.250000

**Comment by gdevenyi** [comment]
1.9.16 is two versions behind in terms of minc-toolkit-v2 releases, this reported issue has since been resolved.

@vfonov can you build newer versions of the nistmni containers?

@zhengchencai in the meantime, you will need to use a different method of accessing the binaries: https://bic-mni.github.io/
