### ISSUE TITLE
Use OpenSuse build service to offer packages

### ISSUE THREAD

**Issue by gdevenyi** [BIC-MNI/minc-toolkit-v2#29]
To automate building of packages (and maybe of development head?)

Can build automatically for all major distros.

https://build.opensuse.org/

**Comment by gdevenyi** [comment]
https://en.opensuse.org/openSUSE:Build_Service_Tutorial

**Comment by gdevenyi** [comment]
Alternatively:
https://bintray.com/

**Comment by vfonov** [comment]
OK, automating building with OpenSuse buld service will require extensive changes to the CMakeLists , since it doesn't allow downloading external sources during build. 
See example log here: https://build.opensuse.org/package/live_build_log/home:vfonov/minc-toolkit-v2/openSUSE_Factory/i586

bintray.com does not allow building , only binary packages distribution.

**Comment by gdevenyi** [comment]
Oh shoot that's unfortunate.

Can you commit/share the deb/rpm build scripts you're using? I have some experiments I'd like to do to see if I can do some automated builds.

**Comment by vfonov** [comment]
https://build.opensuse.org/package/show/home:vfonov/minc-toolkit-v2 - I think .deb scripts will require more debugging - I didn't try to fix them.

**Comment by gdevenyi** [comment]
Thanks.

Upon doing some more reading last night, this https://github.com/tarantool/build looks promising
